- hosts: all
  become: yes
  tasks:
    - name: create the 'k8sadmin' user
      user: name=k8sadmin append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'k8sadmin' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'k8sadmin ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the k8sadmin user
      authorized_key: user=k8sadmin key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub